# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/events', type: :request do
  let(:user) { create(:user) }
  let(:admin_user) { create(:user, :officer) }

  # This should return the minimal set of attributes required to create a valid
  # Event. As you add validations to Event, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      title: 'Test Event',
      date: 1.week.from_now,
      end_time: 1.week.from_now + 2.hours,
      location: 'Test Location',
      description: 'Test description',
    }
  end

  let(:invalid_attributes) do
    {
      title: '',
      date: nil,
    }
  end

  before do
    # Sign in the user for authentication
    sign_in user
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Event.create! valid_attributes
      get events_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      event = Event.create! valid_attributes
      get event_url(event)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    context 'as admin user' do
      before do
        sign_in admin_user
      end

      it 'renders a successful response' do
        get new_event_url
        expect(response).to be_successful
      end
    end

    context 'as regular user' do
      it 'denies access' do
        get new_event_url
        expect(response).to redirect_to(root_path)
      end
    end
  end

  describe 'GET /edit' do
    context 'as admin user' do
      before do
        sign_in admin_user
      end

      it 'renders a successful response' do
        event = Event.create! valid_attributes
        get edit_event_url(event)
        expect(response).to be_successful
      end
    end

    context 'as regular user' do
      it 'denies access' do
        event = Event.create! valid_attributes
        get edit_event_url(event)
        expect(response).to redirect_to(root_path)
      end
    end
  end

  describe 'POST /create' do
    context 'as admin user' do
      before do
        sign_in admin_user
      end

      context 'with valid parameters' do
        it 'creates a new Event' do
          expect do
            post events_url, params: { event: valid_attributes }
          end.to change(Event, :count).by(1)
        end

        it 'redirects to the created event' do
          post events_url, params: { event: valid_attributes }
          expect(response).to redirect_to(event_url(Event.last))
        end
      end

      context 'with invalid parameters' do
        it 'does not create a new Event' do
          expect do
            post events_url, params: { event: invalid_attributes }
          end.to change(Event, :count).by(0)
        end

        it "renders a response with 422 status (i.e. to display the 'new' template)" do
          post events_url, params: { event: invalid_attributes }
          expect(response).to have_http_status(:unprocessable_entity)
        end
      end
    end

    context 'as regular user' do
      it 'denies access' do
        post events_url, params: { event: valid_attributes }
        expect(response).to redirect_to(root_path)
      end
    end
  end

  describe 'PATCH /update' do
    context 'as admin user' do
      let(:new_attributes) do
        {
          title: 'Updated Event Title',
          location: 'Updated Location',
        }
      end

      before do
        sign_in admin_user
      end

      context 'with valid parameters' do
        it 'updates the requested event' do
          event = Event.create! valid_attributes
          patch event_url(event), params: { event: new_attributes }
          event.reload
          expect(event.title).to eq('Updated Event Title')
          expect(event.location).to eq('Updated Location')
        end

        it 'redirects to the event' do
          event = Event.create! valid_attributes
          patch event_url(event), params: { event: new_attributes }
          event.reload
          expect(response).to redirect_to(event_url(event))
        end
      end

      context 'with invalid parameters' do
        it "renders a response with 422 status (i.e. to display the 'edit' template)" do
          event = Event.create! valid_attributes
          patch event_url(event), params: { event: invalid_attributes }
          expect(response).to have_http_status(:unprocessable_entity)
        end
      end
    end

    context 'as regular user' do
      it 'denies access' do
        event = Event.create! valid_attributes
        patch event_url(event), params: { event: { title: 'Updated Title' } }
        expect(response).to redirect_to(root_path)
      end
    end
  end

  describe 'DELETE /destroy' do
    context 'as admin user' do
      before do
        sign_in admin_user
      end

      it 'destroys the requested event' do
        event = Event.create! valid_attributes
        expect do
          delete event_url(event)
        end.to change(Event, :count).by(-1)
      end

      it 'redirects to the events list' do
        event = Event.create! valid_attributes
        delete event_url(event)
        expect(response).to redirect_to(events_url)
      end
    end

    context 'as regular user' do
      it 'denies access' do
        event = Event.create! valid_attributes
        delete event_url(event)
        expect(response).to redirect_to(root_path)
      end
    end
  end

  describe 'Approved excuses display' do
    let(:event) { Event.create! valid_attributes }
    let(:excused_user1) { create(:user, approval_status: 'approved') }
    let(:excused_user2) { create(:user, approval_status: 'approved') }

    before do
      Excuse.create!(member: excused_user1, event: event, reason: 'Sick', status: 'approved', proof_link: 'https://example.com/proof1')
      Excuse.create!(member: excused_user2, event: event, reason: 'Doctor', status: 'approved', proof_link: 'https://example.com/proof2')
    end

    context 'as admin user' do
      before do
        sign_in admin_user
      end

      describe 'GET /show' do
        it 'displays approved excuses count and names' do
          get event_url(event)
          expect(response).to be_successful
          expect(response.body).to include('Approved Excuses')
          expect(response.body).to include(excused_user1.full_name)
          expect(response.body).to include(excused_user2.full_name)
        end
      end

      describe 'GET /index' do
        it 'displays approved excuses count in event cards' do
          get events_url
          expect(response).to be_successful
          expect(response.body).to include('excuse')
        end
      end
    end

    context 'as regular user' do
      describe 'GET /show' do
        it 'does not display approved excuses section' do
          get event_url(event)
          expect(response).to be_successful
          expect(response.body).not_to include('Approved Excuses')
        end
      end
    end
  end

  describe 'JSON requests' do
    let(:event) { Event.create! valid_attributes }

    before do
      sign_in admin_user
    end

    describe 'GET /show' do
      it 'returns JSON format' do
        get event_url(event, format: :json)
        expect(response).to be_successful
        expect(response.content_type).to include('application/json')
      end
    end

    describe 'POST /create' do
      it 'returns JSON format on success' do
        post events_url(format: :json), params: { event: valid_attributes }
        expect(response).to be_successful
        expect(response.content_type).to include('application/json')
      end

      it 'returns JSON format on error' do
        post events_url(format: :json), params: { event: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to include('application/json')
      end
    end

    describe 'PATCH /update' do
      it 'returns JSON format on success' do
        patch event_url(event, format: :json), params: { event: { title: 'Updated' } }
        expect(response).to be_successful
        expect(response.content_type).to include('application/json')
      end

      it 'returns JSON format on error' do
        patch event_url(event, format: :json), params: { event: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to include('application/json')
      end
    end

    describe 'DELETE /destroy' do
      it 'returns no content' do
        delete event_url(event, format: :json)
        expect(response).to have_http_status(:no_content)
      end
    end
  end
end
